name: iml-2023
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.24.2
  - pandas=1.5.3
  - matplotlib=3.5.2
  - jupyterlab=3.3.3
  - scikit-learn=1.2.2
  - pip=22.1.2
  - seaborn=0.11.2
  - ipykernel=5.5.5
  - openpyxl=3.0.9
  - xgboost=1.7.4